version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  golang:                                # 自定义容器名称
    build:
      context: ./golang                  # 指定构建使用的 Dockerfile 文件
    image: go1.18
    container_name: go1.18
    environment:
      - TZ=${TZ}
      - LANG=C.UTF-8
    volumes:
      - /home/uos/dde-go/src:/usr/src
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend

  etcd1:
    image: bitnami/etcd
    container_name: etcd1
    networks:
      - backend
    ports:
      - "23791:2379"
      - "23801:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                      # 初始化集群状态
  
  etcd2:
    image: bitnami/etcd
    container_name: etcd2
    networks:
      - backend
    ports:
      - "23792:2379"
      - "23802:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                      # 初始化集群状态

  etcd3:
    image: bitnami/etcd
    container_name: etcd3
    networks:
      - backend
    ports:
      - "23793:2379"
      - "23803:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster             # 在启动期间用于 etcd 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380 # 为启动初始化集群配置
      - ETCD_INITIAL_CLUSTER_STATE=new                      # 初始化集群状态

  etcd_web:
    image: evildecay/etcdkeeper
    container_name: etcd_web
    networks:
      - backend
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      - HOST=etcd_web
    ports:
      - "8091:8080"

  db:
    image: mysql
    hostname: "mysql"
    ports:
      - "53306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./data/mysql/conf:/etc/mysql/conf.d
      - ./data/mysql/data:/var/lib/mysql
    networks:
      - backend
    
  cache:
    image: redis
    hostname: "redis"
    ports:
      - "56379:6379"
    volumes:
      - ./data/redis/data:/data
      - ./data/redis:/etc/redis
    command: /bin/bash -c "redis-server /etc/redis/redis.conf"
    networks:
      - backend

