version: "3"
services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME: uos
      - MONGO_INITDB_ROOT_PASSWORD: uos123

  ## mongo 的web界面
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
  #     - ME_CONFIG_MONGODB_SERVER=mongodb